version: "3"

services:
  ### PostgreSQL
  postgresql-server:
    image: library/postgres:9.6
    environment:
      - POSTGRES_PASSWORD=mysecretpassword

  postgresql-exporter:
    image: wrouesnel/postgres_exporter
    environment:
      - DATA_SOURCE_NAME=postgresql://postgres:mysecretpassword@postgresql-server:5432/?sslmode=disable
