version: "3"
services:
  node-exporter:
    image: prom/node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - --collector.filesystem.ignored-mount-points
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
  http-simulator:
    image: pierrevincent/prom-http-simulator
    ports:
      - 8884:8080
  blackbox-exporter:
    image: prom/blackbox-exporter
    ports:
      - 8885:9115
    volumes:
      - ${PWD}/config/blackbox.yaml:/etc/config/blackbox.yaml
    command: --config.file=/etc/config/blackbox.yaml
