modules:
  https_2xx:
    prober: http
    http:
      tls_config:
        insecure_skip_verify: false
  http_post_2xx:
    prober: http
    http:
      method: POST
  tcp_connect:
    prober: tcp
  http_2xx_v6:
    prober: http
    http:
      tls_config:
        insecure_skip_verify: false
      preferred_ip_protocol: "ip6"